version: "2"

services:

  deploy:
    image: quay.io/rekurzia/aws-cli-docker
    volumes:
      - ./:/code
    tty: true
    working_dir: /code
    environment:
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
    command: s3 cp src s3://slides.webelement.sk --recursive --acl public-read --region eu-central-1
